server:
    port: 8081

management:
    endpoint:
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: shutdown

spring:
    data:
        mongodb:
            uri: ${MONGO_CREDENTIALS}
