name: Deploy to EC2

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0' 

    - name: Install PM2
      run: npm install -g pm2

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo ln -s "~/.nvm/versions/node/v20.10.0/bin/node" "/usr/local/bin/node"
          sudo ln -s "~/.nvm/versions/node/v20.10.0/bin/npm" "/usr/local/bin/npm"
          sudo ln -s "~/.nvm/versions/node/v20.10.0/bin/pm2" "/usr/local/bin/pm2"
          cd ~/Europe-Saviors/app/server/
          git pull origin main
          npm ci
          npm run build
          pm2 restart myApp
