name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Conductor:
    runs-on: ubuntu-latest

    env: 
      MONGO_CREDENTIALS: ${{ secrets.MONGO_CREDENTIALS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      - name: Build Frontend
        run: npm run build
        working-directory: ./app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract Runner IP Address
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist Runner IP Address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            scp -r ./app/public/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/Europe-Saviors/app/public/
          #export NVM_DIR=~/.nvm
          #source ~/.nvm/nvm.sh
          #cd ~/Europe-Saviors
          #git pull origin main 
          #export MONGO_CREDENTIALS=$MONGO_CREDENTIALS
      - name: Revoke Runner IP Address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
